language: ruby

rvm:
  - 2.3.1

cache:
  bundler: true

bundler_args: --without production

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN bundle exec rake spec
